// Generated by CoffeeScript 1.9.3
var FabricLayer, fabricInit,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

FabricLayer = (function(superClass) {
  extend(FabricLayer, superClass);

  FabricLayer.prototype.map = null;

  function FabricLayer(options) {
    FabricLayer.__super__.constructor.call(this, options);
    this.on('postcompose', this.postcompose_, this);
    this.setSource(new ol.source.Vector());
  }

  FabricLayer.prototype.postcompose_ = function(event) {
    var context, oneMeterPx, pixelRatio, r, r2, resolutionAtCoords, view;
    if (this.map == null) {
      return;
    }
    context = event.context;
    pixelRatio = event.frameState.pixelRatio;
    view = this.map.getView();
    resolutionAtCoords = view.getProjection().getPointResolution(event.frameState.viewState.resolution, view.getCenter());
    oneMeterPx = (1 / resolutionAtCoords) * pixelRatio;
    r = event.frameState.viewState.rotation;
    r2 = this.rotation * Math.PI / 180;
    if (window.canvas == null) {
      fabricInit(context, this);
    }
    canvas.zoomToPoint(new fabric.Point(canvas.width / 2, canvas.height / 2), oneMeterPx);
    return canvas.renderAllOnTop();
  };

  return FabricLayer;

})(ol.layer.Vector);

fabricInit = (function(_this) {
  return function(context, layer) {
    var blue, red;
    window.canvas = new fabric.Canvas(context.canvas, {
      width: context.canvas.width,
      height: context.canvas.height,
      renderOnAddRemove: true
    });
    window.onresize = function() {
      canvas.setWidth(document.documentElement.clientWidth);
      return canvas.setHeight(document.documentElement.clientHeight);
    };
    fabric.Object.prototype.scaleX = 1;
    fabric.Object.prototype.scaleY = 1;
    fabric.Object.prototype.originX = 'center';
    fabric.Object.prototype.originY = 'center';
    fabric.Object.prototype.transparentCorners = true;
    fabric.Object.prototype.cornerColor = "#488BD4";
    fabric.Object.prototype.borderOpacityWhenMoving = 0.8;
    fabric.Object.prototype.cornerSize = 10;
    canvas._renderAll = canvas.renderAll;
    canvas.renderAll = function() {
      return layer.changed();
    };
    canvas._renderTop = canvas.renderTop;
    canvas.renderTop = function() {
      return layer.changed();
    };
    canvas.renderAllOnTop = function() {
      var activeGroup, canvasToDrawOn;
      canvasToDrawOn = this.contextTop;
      activeGroup = this.getActiveGroup();
      this.clearContext(this.contextTop);
      this.fire('before:render');
      if (this.clipTo) {
        fabric.util.clipContext(this, canvasToDrawOn);
      }
      this._renderBackground(canvasToDrawOn);
      this._renderObjects(canvasToDrawOn, activeGroup);
      this._renderActiveGroup(canvasToDrawOn, activeGroup);
      if (this.selection && this._groupSelector) {
        this._drawSelection();
      }
      if (this.clipTo) {
        canvasToDrawOn.restore();
      }
      this._renderOverlay(canvasToDrawOn);
      if (this.controlsAboveOverlay && this.interactive) {
        this.drawControls(canvasToDrawOn);
      }
      this.fire('after:render');
      return this;
    };
    red = new fabric.Rect({
      left: canvas.width / 2 - 1,
      top: canvas.height / 2,
      fill: 'red',
      width: 4,
      height: 4,
      angle: 45
    });
    blue = new fabric.Rect({
      left: canvas.width / 2 + 1,
      top: canvas.height / 2,
      fill: 'blue',
      width: 4,
      height: 4,
      angle: 45
    });
    canvas.add(red);
    return canvas.add(blue);
  };
})(this);

//# sourceMappingURL=fabriclayer.js.map
